AllCops:
  Include:
    - 'smart_pension/**/*.rb'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
    -
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
